### ISSUE TITLE
Some species photo icons missing

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#153] opened 2022-07-27 08:56 UTC
There are a few of the new species icons missing from the species lists that appear in the user's statistics lists e.g. High Brown Fritillary, Dingy Skipper.

**Comment by kazlauskis** [comment] 2022-08-04 09:39
The issue with missing icons is that some of the species in the report are subspecies. So it can happen that a user records multiple `Erynnis tages` in the app and then changes one of these on the website (or a verifier corrects it) to a `Erynnis tages tages`. This then creates a new entry in the report which doesn't quite match the species profiles in the app. Essentially the list has multiple entries of the same species - one with a photo and another without. The total counts aren't affected by this and it still shows as 1 out of the total 64 species.

We could do some cleaning up in the app to normalise such lists by merging subspecies to species level, but it would be better to do it at the report level on the website. For now, we will probably leave the subspecies in the list but fix the photo and, also, show it is a subspecies so it doesn't look like a duplicate of the same species.

**Comment by RichardFoxBC** [comment] 2022-08-08 10:28
High Brown Fritillary still showing with no photo icon in my Statistics species report for 2022

**Comment by Vilius-Stankaitis** [comment] 2022-08-08 10:51
Thank you, I will take a look.

**Comment by DavidRoy** [comment] 2022-08-08 10:56
I'm missing photo icons for Dingy Skipper and Holly Blue in my 'All years' report.  But not 'Holly blue' from individual year reports.  Dingy skipper is missing from all reports.

**Comment by Vilius-Stankaitis** [comment] 2022-08-08 12:30
"High Brown Fritillary" does not have the icon, because the scientific name from the app and the report does not match. 

App -> "Fabriciana adippe" 
Report (iRecord) ->  "Argynnis adippe"

Matching on common names is going to be tricky as these can change on the website and have different formatting than what is currently in the app.

**Comment by DavidRoy** [comment] 2022-08-08 13:45
Can you match on taxon_meaning_id which should handle synonymy?  This would need your app list including these IDs and the Indicia report to include the IDs?

**Comment by Vilius-Stankaitis** [comment] 2022-08-09 06:45
Indicia report has taxon_meaning_id, so I only need to add ids to the app list. Maybe there is an existing report for taxon_meaning_id that I could use? Or can someone export it if I provide warehouse_id?

**Closed** 2022-08-10 14:12 UTC
Labels: app

**Comment by kazlauskis** [comment] 2022-08-10 14:29
@DavidRoy just want to double-check something. We have implemented the `taxon_meaning_id` checks for better app-to-reports species matching and it 'mostly' works well. In some cases, we still have to rely on scientific name matching because `taxon_meaning_id` is different for sub-species. Do you know why, like in this case, the `taxon_meaning_id` differs between the two species?

<img width="309" alt="Screenshot 2022-08-10 at 17 20 47" src="https://user-images.githubusercontent.com/7383162/183926588-9a5a0ce5-86b7-4da6-b94b-e4a9d13276fb.png">

**Comment by DavidRoy** [comment] 2022-08-11 12:18
@kazlauskis It is right that sub-species would have different meaning_id as they are different taxonomic concepts.  However, we should not have sub-species data in the app - certainly, the app should not submit sub-species occurrences.  There was a problem with the UKSI and Dingy Skipper, so perhaps this is a legacy problem (although the date on the example sub-species record above is recent)? Or maybe there is a problem if records are edited (e.g. redetermined) within the iRecord verification system.

**Comment by kazlauskis** [comment] 2022-08-11 12:49
Thanks, I think this is the latter case. Records can be modified elsewhere. If a verifier assigns a species to some sub-species, ElasticSearch reports return sub-species to the app. And the app doesn't have a solid way to connect sub-species to species but does some scientific name reformatting to try to match the names.

**Comment by DavidRoy** [comment] 2022-08-11 12:52
I'll raise a separate issue for this to review the existing data and assignment to sub-species
