### ISSUE TITLE
Issue: Error 500 

### ISSUE THREAD

**Issue by robin-hutchinson** [NERC-CEH/irecord-butterflies-app#181] opened 2024-09-16 16:19 UTC
### Describe the issue

"Continue to get this error message ["Request failed with status code 500"] when trying to see my stats.
Been doing it for a few weeks now.
Uninstall and reinstall app a few times and no change."
 - From email from recorder

### App Version

Most recent (has tried re-installing)

### Device

Galaxy A54

### Screenshots

![1000041222](https://github.com/user-attachments/assets/748fad2f-6aa3-419b-b640-c5a8c8c3211b)
![1000041255](https://github.com/user-attachments/assets/85e450d4-4e57-4478-827c-1b96635bea28)
![1000041253](https://github.com/user-attachments/assets/21146486-7dda-4f32-89da-2acf71542bc9)

**Comment by kazlauskis** [comment] 2024-09-17 05:11
Duplicate of #180

**Closed by kazlauskis** 2024-09-17 05:11 UTC
